#!/usr/bin/env python3
"""
hallucination_judge.py
======================
Grades whether the synthesised response accurately reflects the
retrieved customer record without hallucinating.

Two complementary approaches:
  1. BERTScore  — fast, token-level semantic similarity
  2. LLM-as-Judge — slow but nuanced; uses a small judge model via vLLM

Both return a score in [0, 1]:
  1.0 = fully grounded, no hallucination detected
  0.0 = complete hallucination

Usage:
    from hallucination_judge import HallucinationJudge, JudgeConfig
    judge = HallucinationJudge(config=JudgeConfig(backend="bertscore"))
    score = judge.score(final_response, retrieved_record)
"""

import json
import re
import time
import numpy as np
from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List


# ── Config ────────────────────────────────────────────────────────────────────
@dataclass
class JudgeConfig:
    backend: str = "bertscore"          # "bertscore" | "llm" | "combined"
    bertscore_model: str = "microsoft/deberta-xlarge-mnli"
    bertscore_lang: str = "en"
    judge_model_id: str = "Qwen/Qwen2.5-3B-Instruct"  # small fast judge
    judge_max_tokens: int = 128
    combined_weights: tuple = (0.5, 0.5)  # (bertscore, llm)
    device: str = "cpu"


JUDGE_SYSTEM = (
    "You are a strict hallucination evaluator for a telecom voice assistant.\n"
    "Given a RETRIEVED customer record and a RESPONSE generated by an AI assistant,\n"
    "evaluate whether the response accurately reflects the retrieved information.\n\n"
    "Score the response on a scale from 0 to 10:\n"
    "  10 = Perfectly accurate, all facts match the record, no extra claims\n"
    "   7 = Minor omissions but no wrong facts\n"
    "   4 = Some wrong facts or vague hedging that obscures truth\n"
    "   1 = Major hallucinations, completely wrong customer data\n"
    "   0 = No relevant information provided at all\n\n"
    "Reply with ONLY a single integer from 0-10 and nothing else."
)

JUDGE_TEMPLATE = (
    "RETRIEVED RECORD:\n{record}\n\n"
    "AI ASSISTANT RESPONSE:\n{response}\n\n"
    "Score (0-10):"
)


# ── BERTScore Judge ───────────────────────────────────────────────────────────
class BERTScoreJudge:
    """
    Uses BERTScore to compare the synthesized response against a
    flattened ground-truth string derived from the retrieved record.
    """

    def __init__(self, model: str = "microsoft/deberta-xlarge-mnli",
                 lang: str = "en", device: str = "cpu"):
        try:
            from bert_score import score as bert_score_fn
            self._score_fn = bert_score_fn
            self._model    = model
            self._lang     = lang
            self._device   = device
            self._available = True
        except ImportError:
            print("[WARN] bert_score not installed. Falling back to token-overlap judge.")
            self._available = False

    def _record_to_str(self, record: Dict[str, Any], response: str = "") -> str:
        """
        Flatten a retrieved record to a natural-language reference string.
        Dynamically filters database identifiers (phone, customer_id) unless 
        they are explicitly mentioned in the response to avoid artificial penalties.
        """
        parts = []
        # Name, plan, and balance are standard verbal facts expected in synthesis
        for key in ("name", "plan", "balance"):
            if key in record and record[key]:
                parts.append(f"{key}: {record[key]}")
        
        # Only include phone and customer_id in reference if they are present in the response
        for key in ("phone", "customer_id"):
            if key in record and record[key]:
                val_str = str(record[key]).lower()
                clean_val = re.sub(r"\D", "", val_str)  # strip non-digits for phone comparisons
                lowered_response = response.lower()
                if val_str in lowered_response or (clean_val and clean_val in lowered_response):
                    parts.append(f"{key}: {record[key]}")
                    
        return ". ".join(parts)

    def _token_overlap_fallback(self, response: str, reference: str) -> float:
        """Simple token overlap (Jaccard) as last resort."""
        r_tok = set(re.sub(r"[^\w]", " ", response.lower()).split())
        ref_tok = set(re.sub(r"[^\w]", " ", reference.lower()).split())
        if not ref_tok:
            return 0.0
        return len(r_tok & ref_tok) / len(ref_tok)

    def score(self, response: str, record: Dict[str, Any]) -> float:
        reference = self._record_to_str(record, response)
        if not response.strip() or not reference.strip():
            return 0.0

        if self._available:
            # 1. Attempt official BERTScore with its built-in baseline rescaling
            try:
                P, R, F = self._score_fn(
                    cands=[response],
                    refs=[reference],
                    model_type=self._model,
                    lang=self._lang,
                    device=self._device,
                    verbose=False,
                    rescale_with_baseline=True,
                )
                rescaled = float(F[0].item())
                return round(min(1.0, max(0.0, rescaled)), 4)
            except Exception:
                # 2. Offline fallback: manual rescaling using a safer empirical floor
                try:
                    P, R, F = self._score_fn(
                        cands=[response],
                        refs=[reference],
                        model_type=self._model,
                        lang=self._lang,
                        device=self._device,
                        verbose=False,
                        rescale_with_baseline=False,
                    )
                    raw_f = float(F[0].item())
                    # Empirical floor of 0.72 accounts for DeBERTa similarity baselines
                    rescaled = max(0.0, (raw_f - 0.72) / 0.28)
                    return round(min(1.0, rescaled), 4)
                except Exception as e:
                    print(f"[WARN] BERTScore evaluation failed ({e}), falling back to token overlap")

        return round(self._token_overlap_fallback(response, reference), 4)


# ── LLM Judge ─────────────────────────────────────────────────────────────────
class LLMJudge:
    """
    Uses a small LLM loaded via vLLM to assign a 0-10 score,
    which is normalised to [0,1].
    """

    def __init__(self, model_id: str, max_tokens: int = 128):
        try:
            from vllm import LLM
            from vllm.sampling_params import SamplingParams
            self._llm = LLM(
                model=model_id,
                trust_remote_code=True,
                dtype="bfloat16",
                gpu_memory_utilization=0.25,   # small judge model
                max_model_len=1024,
                disable_log_stats=True,
            )
            self._params = SamplingParams(
                temperature=0.0, max_tokens=max_tokens
            )
            self._available = True
        except Exception as e:
            print(f"[WARN] LLMJudge init failed ({e}). Judge unavailable.")
            self._available = False

    def _build_prompt(self, response: str, record: Dict[str, Any]) -> str:
        record_str = json.dumps(record, indent=2)
        return (
            f"<|im_start|>system\n{JUDGE_SYSTEM}<|im_end|>\n"
            f"<|im_start|>user\n"
            f"{JUDGE_TEMPLATE.format(record=record_str, response=response)}"
            f"<|im_end|>\n<|im_start|>assistant\n"
        )

    def score(self, response: str, record: Dict[str, Any]) -> Optional[float]:
        if not self._available:
            return None
        prompt = self._build_prompt(response, record)
        try:
            out = self._llm.generate([prompt], self._params)
            text = out[0].outputs[0].text.strip()
            m = re.search(r"\d+", text)
            if m:
                raw = int(m.group())
                return round(min(10, max(0, raw)) / 10.0, 4)
        except Exception as e:
            print(f"[WARN] LLMJudge.score failed: {e}")
        return None


# ── Combined Judge ────────────────────────────────────────────────────────────
class HallucinationJudge:
    """
    Unified interface. Dispatches to BERTScore, LLM, or a weighted combination.
    """

    def __init__(self, config: Optional[JudgeConfig] = None):
        self.config = config or JudgeConfig()
        self._bertscore: Optional[BERTScoreJudge] = None
        self._llm_judge: Optional[LLMJudge]       = None

        if self.config.backend in ("bertscore", "combined"):
            self._bertscore = BERTScoreJudge(
                model=self.config.bertscore_model,
                lang=self.config.bertscore_lang,
                device=self.config.device,
            )
        if self.config.backend in ("llm", "combined"):
            self._llm_judge = LLMJudge(
                model_id=self.config.judge_model_id,
                max_tokens=self.config.judge_max_tokens,
            )

    def score(self, response: str,
              record: Optional[Dict[str, Any]]) -> float:
        """
        Returns hallucination score in [0, 1].
        1.0 = no hallucination, 0.0 = complete hallucination.
        """
        if not record:
            # No record retrieved — check if response says "not found" correctly
            lowered = response.lower()
            if any(w in lowered for w in ("not found", "couldn't find",
                                          "no account", "unable to locate")):
                return 1.0   # correctly acknowledged
            return 0.3       # gave vague response with no factual grounding

        bs_score  = None
        llm_score = None

        if self._bertscore:
            bs_score = self._bertscore.score(response, record)

        if self._llm_judge:
            llm_score = self._llm_judge.score(response, record)

        if self.config.backend == "bertscore":
            return bs_score if bs_score is not None else 0.5
        if self.config.backend == "llm":
            return llm_score if llm_score is not None else 0.5
        if self.config.backend == "combined":
            w_bs, w_llm = self.config.combined_weights
            scores, weights = [], []
            if bs_score is not None:
                scores.append(bs_score);  weights.append(w_bs)
            if llm_score is not None:
                scores.append(llm_score); weights.append(w_llm)
            if not scores:
                return 0.5
            total_w = sum(weights)
            return round(sum(s*w for s,w in zip(scores,weights)) / total_w, 4)

        return 0.5

    def score_batch(self, items: List[Dict]) -> List[float]:
        """
        items: list of {"response": str, "record": dict}
        Returns list of scores.
        """
        return [self.score(i["response"], i.get("record")) for i in items]
